# Generated by Django 4.2 on 2023-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="completion_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
